### PR TITLE
Support high dimensional data via screening

### PR DESCRIPTION
**Pull request by jeremyrcoyle**
A number of changes with the general goal of adding support for larger datasets, and improving overall functionality
* New argument `screen_basis` (default=TRUE) applies a screening algorithm to select basis functions associated with Y
* New argument `screen_lambda` (default=TRUE) applies a screening algorithm to select the set of lambdas that `cv.glmnet` chooses
* New argument `id` used to generate cross-validation folds for `glmnet`
* New argument `offset` used in fitting and prediction in `glmnet`
* Argument `degrees` changed to `max_degree` (new default=3), to better reflect argument's intention
* Remove lassi section of vignette
* `predict.hal9001` uses prediction from `glmnet` when available (which it is now by default, as `return_lasso` is now true by default)

### CODE REVIEW

**Comment by jeremyrcoyle** [comment]
@wilsoncai1992, @nhejazi for the purposes of simulation with hal as defined in theory these settings should help:

* `screen_basis=FALSE`
* `screen_lambda=FALSE`
* `max_degrees=NULL`

**Comment by wilsoncai1992** [comment]
In general, great job Jeremy! Faster HAL = more papers = everyone happy

**Comment by jeremyrcoyle** [comment]
I think I removed one test that had to do with HAL having a lower MSE than HAL wrapped in super Learner, which need not be the case. A few other tests I cleaned up a bit. I'll add the predict one lambda to this PR since it's already a bit of an omnibus

**Comment by jeremyrcoyle** [comment]
Modified this PR so that screening is off by default. We need more testing here, but it's useful in enough situations that i'll merge once tests pass.

**Pull request merged**
