### PR TITLE
Return basis functions optionally

### PR DESCRIPTION
**Pull request by nhejazi**
Currently, `fit_hal` returns several bits of information on the basis functions used in its Lasso step, including `basis_list` and the `copy_map` (for de-duping basis functions); however, it is still a somewhat involved procedure to reconstruct the `x_basis` data structure fed into `cv.glmnet`, `glmnet`, or the custom Lasso procedure from this output alone. This PR adds the option to directly return the `x_basis` data structure (defaulting to `FALSE`). This is useful for new ideas in estimating the conditional average treatment effect (CATE) in settings where causal quantities are of interest.

### CODE REVIEW

**Comment by wilsoncai1992** [comment]
downstream of my code breaks. would be better if I am notified when the default output changes.

**Comment by nhejazi** [comment]
@wilsoncai1992 Would you mind clarifying how this breaks your code? Please note that this PR adds the additional argument `return_x_basis`, but the default output remains unchanged (as that argument is set to `FALSE` by default). Perhaps something else is broken?

**Comment by wilsoncai1992** [comment]
i always expect returning x_basis

**Comment by wilsoncai1992** [comment]
nvm sorry! I confused x_basis v.s. basis_list. You are correct.

**Pull request merged**
