### PR TITLE
add x_unpenalized functionality

### PR DESCRIPTION
**Pull request by wilsoncai1992**
This adds the option for the user to add extra covariates into the design matrix, and the covariate will not be subject to L-1 penalization. Will come in handy for always including the treatment variable for Q regression.

Extensive unit testing is included to make sure the prediction and training phase `x_unpenalized` format are exactly the same. 

`make pr` is passing

### CODE REVIEW

**Comment by wilsoncai1992** [comment]
travis build is passing on `release` and failing on `devel`. However, the master branch is also failing on `devel`: https://travis-ci.org/tlverse/hal9001/jobs/439880134. Seems to be some problem with the new R version? appveyor has been failing consistently before this commit

**Comment by nhejazi** [comment]
@wilsoncai1992 --- thanks for this contribution. I haven't had a chance to take a look at the implementation yet but will provide a review this week. You're right about the unit test failure in `r-devel` and CI problems. I've removed the offending unit test (didn't seem well thought out upon a re-read) and made minor changes to the CI configuration to fix these issues.

**Comment by wilsoncai1992** [comment]
Thanks for taking time to review! Let me know in the mean time what I need
to change.

**Comment by nhejazi** [comment]
Looks like cf375cb fixes the residual build issues. I'll provide a review of the new functionality later today.

**Comment by wilsoncai1992** [comment]
thank you!

**Comment by wilsoncai1992** [comment]
merged.

**Pull request merged**
