### PR TITLE
Updates to single glmnet procedure

### PR DESCRIPTION
**Pull request by nhejazi**
This PR makes breaking changes to how some of the arguments in `fit_hal` are used to call `glmnet` in fitting Lasso models over a pre-specified range of tuning parameter values. These changes improve how `hal9001` handles such a case and are required for the density estimation functionality exposed in the `haldensify` R package.

### CODE REVIEW

**Comment by nhejazi** [comment]
@wilsoncai1992 -- please note that this PR introduces breaking changes that will affect (at least) some of your simulation code. The changes affect only how a new argument is used internally by `fit_hal` so it is still possible to extract the output you rely on but will require minor changes to your code. If possible, please take a look through this PR soon, as I'd like to merge this soon (for work related to the density estimation procedure required to evaluate the counterfactual mean under a stochastic intervention).

**Comment by jeremyrcoyle** [comment]
`fit_glmnet` seems like a confusing name for the new argument, since setting it to false also involves fitting glmnets? Maybe something like `select_lambda` or `do_cv`?

**Comment by wilsoncai1992** [comment]
@nhejazi you are removing the ability to fit glmnet with a single lambda?

**Comment by nhejazi** [comment]
@jeremyrcoyle --- thanks for the input. I agree, the current argument name is vague (and a produce of a lack of creativity). Happy to change it: would `cv_select` be better? I think that conveys that in such a case, i.e., `cv_select = TRUE`, `cv.glmnet` would be used to find an optimal value of the tuning parameter (the default would then be `TRUE` instead of the current `fit_glmnet = FALSE`).

@wilsoncai1992 --- yes, I like (and need) the functionality you originally contributed. The main change here is that you can still fit for a single lambda by feeding that value in and specifying `fit_glmnet = TRUE`, but you can also now do this with a sequence of lambdas if you wanted. Before, lines 94-99 locked in the use of only a single lambda when fitting `glmnet` even though it handles a sequence of them by default. That said, don't change your code until we finalize the argument name.

**Comment by wilsoncai1992** [comment]
> @jeremyrcoyle --- thanks for the input. I agree, the current argument name is vague (and a product of a lack of creativity). Happy to change it: would `cv_select` be better? I think that conveys that in such a case, i.e., `cv_select = TRUE`, `cv.glmnet` would be used to find an optimal value of the tuning parameter (the default would then be `TRUE` instead of the current `fit_glmnet = FALSE`).
> 
> @wilsoncai1992 --- yes, I like (and need) the functionality you originally contributed. The main change here is that you can still fit for a single lambda by feeding that value in and specifying `fit_glmnet = TRUE`, but you can also now do this with a sequence of lambdas if you wanted. Before, lines 94-99 locked in the use of only a single lambda when fitting `glmnet` even though it handles a sequence of them by default. That said, don't change your code until we finalize the argument name.

This is awesome! Makes a lot of sense!

**Comment by jeremyrcoyle** [comment]
@nhejazi `cv_select=TRUE` seems more clear. Thanks

**Pull request merged**
