### PR TITLE
Halscreenz

### PR DESCRIPTION
**Pull request by YuZhang2019**
Hi Jeremy,

Thanks a lot for your patience. I have finally learned how to pull request. I wrote 2 R scripts, one is the screening function named halscreen2, the other is a test document named test_halscreen2. They are all on the front page, not in any folders, so it'll be easy to find them. I would appreciate any information you provide to modify these codes. Thank you so much!

Best,
Yu

### CODE REVIEW

**Comment by jeremyrcoyle** [comment]
Hi Yu, please move the files to the R and tests/testthat folders respectively. The folder structure is important.

**Comment by YuZhang2019** [comment]
I will do that immediately. Thanks!
________________________________

**Comment by jeremyrcoyle** [comment]
You'll also need to document your functions as described here: http://r-pkgs.had.co.nz/man.html . Once that's done, you can make sure everything is correct locally by running make check from the terminal.

**Comment by nhejazi** [comment]
Also please bump https://github.com/tlverse/hal9001/blob/master/DESCRIPTION#L3 to 0.2.6 in your next PR.

**Pull request closed without merging**
