### PR TITLE
General family

### PR DESCRIPTION
**Pull request by Larsvanderlaan**
I made some simple changes to support passing in family objects. I think these are all the changes needed for this functionality. I might be missing something.

### CODE REVIEW

**Comment by Larsvanderlaan** [comment]
If these changes look good then I will add documentation and tests.

**Comment by jeremyrcoyle** [comment]
Looks good! Should be ready to merge after docs + tests

**Comment by nhejazi** [comment]
Seems good to me, thanks! To confirm, this adds support similar to what's currently provided by `glmnet` for fitting arbitrary families, right? My understanding has been that this would be slower than the native family implementations but has the upside of providing general support.

**Comment by Larsvanderlaan** [comment]
Added some documentation and basic tests. For some weird reason cv.glmnet throws a ton of "length not equal" warnings when you pass in a sparse matrix. So I decided to always convert sparse matrices to regular matrices for family objects. The predictions in both cases are correct. Maybe we should use sparse matrices and suppress the glmnet warnings? Its a bit weird.

**Pull request merged**
